version: "{build}"

platform:
  - x86
  - x64
  - arm64

clone_folder: c:\ext\Go\src\service

environment:
  GOPATH: c:\ext\go

install:
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - go install -v ./...

test_script:
  - go test -v -tags su ./...
